# Generated by Django 3.1.2 on 2020-11-12 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('zoom', models.FloatField()),
                ('centerX', models.FloatField()),
                ('centerY', models.FloatField()),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gps')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.picture')),
            ],
        ),
    ]
