# Generated by Django 3.1.2 on 2020-11-15 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='centerX',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='centerY',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='gps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gps'),
        ),
        migrations.AlterField(
            model_name='map',
            name='zoom',
            field=models.FloatField(null=True),
        ),
    ]
