# Generated by Django 3.1.2 on 2020-11-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201115_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='gps',
        ),
        migrations.AddField(
            model_name='gps',
            name='map_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.map'),
        ),
    ]
